/*
  DO NOT EDIT THIS FILE: This file will be overwritten after submitting.
  If you want to add your own code, do so in the main.js file within BP/scripts/main.js
*/

import { system, world } from '@minecraft/server';
import "../main"; // User provided main function
import luckyEventData from '../events'; // User provided lucky block events

// This function handles rolling a lucky block function that is present in the luckyBlockEvents object array.
export function rollLuckyBlock(ctx) {
    if (luckyEventData.author == "Your username here") {
        world.sendMessage("§eWarning: please set the author field in BP/events.js to your username")
    }
    const luckyBlockEvents = luckyEventData.events

    if (luckyBlockEvents.length == 0) {
        world.sendMessage("§cYou have not added any events to events.js.")
        world.sendMessage("§cTry importing your events and run /reload to see them in the game.")
        return
    }

    const eventIndex = Math.floor(Math.random() * luckyBlockEvents.length);
    const selectedEvent = luckyBlockEvents[eventIndex]

    if (typeof selectedEvent !== "function") {
        world.sendMessage("§cThere was an error running one of your events.")
        world.sendMessage(`§cEvent at index ${eventIndex} is ${typeof selectedEvent}. Expected: function`)
        return
    }

    try {
        selectedEvent(ctx);
    } catch (err) {
        world.sendMessage("§cThere was an error running one of your events.")
        world.sendMessage("§cView the reason in the content log.")
        throw err
    }
}

system.beforeEvents.startup.subscribe(({ blockComponentRegistry }) => {
    blockComponentRegistry.registerCustomComponent('bao_30k:lucky_block', {
        onPlayerBreak: (e => {
            if (!e.player) return
            const ctx = {
                block: e.block,
                brokenBlockPermutation: e.brokenBlockPermutation,
                dimension: e.block.dimension,
                player: e.player,
            }
            rollLuckyBlock(ctx);
        })
    })
})